#define BUTTON_DOWN_PIN 13
#define BUTTON_S_PIN 12
#define BUTTON_RIGHT_PIN 14
#define BUTTON_ON_PIN 19

#define BUTTON_SINGLE_CLICK_HOLD_DURATION 250
#define BUTTON_COMBO_CLICK_HOLD_DURATION 3000